#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v4
# autospec commit: da8b975
#
Name     : wireplumber
Version  : 0.4.82
Release  : 13
URL      : https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.82/wireplumber-0.4.82.tar.gz
Source0  : https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.82/wireplumber-0.4.82.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: wireplumber-bin = %{version}-%{release}
Requires: wireplumber-data = %{version}-%{release}
Requires: wireplumber-lib = %{version}-%{release}
Requires: wireplumber-license = %{version}-%{release}
Requires: wireplumber-locales = %{version}-%{release}
Requires: wireplumber-services = %{version}-%{release}
Requires: pipewire
BuildRequires : buildreq-meson
BuildRequires : doxygen
BuildRequires : glib-dev
BuildRequires : gobject-introspection
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libspa-0.2)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(lua)
BuildRequires : pkgconfig(systemd)
BuildRequires : pypi-sphinx
BuildRequires : valgrind
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
WirePlumber
===========
.. image:: https://gitlab.freedesktop.org/pipewire/wireplumber/badges/master/pipeline.svg
:alt: Pipeline status

%package bin
Summary: bin components for the wireplumber package.
Group: Binaries
Requires: wireplumber-data = %{version}-%{release}
Requires: wireplumber-license = %{version}-%{release}
Requires: wireplumber-services = %{version}-%{release}

%description bin
bin components for the wireplumber package.


%package data
Summary: data components for the wireplumber package.
Group: Data

%description data
data components for the wireplumber package.


%package dev
Summary: dev components for the wireplumber package.
Group: Development
Requires: wireplumber-lib = %{version}-%{release}
Requires: wireplumber-bin = %{version}-%{release}
Requires: wireplumber-data = %{version}-%{release}
Provides: wireplumber-devel = %{version}-%{release}
Requires: wireplumber = %{version}-%{release}

%description dev
dev components for the wireplumber package.


%package doc
Summary: doc components for the wireplumber package.
Group: Documentation

%description doc
doc components for the wireplumber package.


%package lib
Summary: lib components for the wireplumber package.
Group: Libraries
Requires: wireplumber-data = %{version}-%{release}
Requires: wireplumber-license = %{version}-%{release}

%description lib
lib components for the wireplumber package.


%package license
Summary: license components for the wireplumber package.
Group: Default

%description license
license components for the wireplumber package.


%package locales
Summary: locales components for the wireplumber package.
Group: Default

%description locales
locales components for the wireplumber package.


%package services
Summary: services components for the wireplumber package.
Group: Systemd services
Requires: systemd

%description services
services components for the wireplumber package.


%prep
%setup -q -n wireplumber-0.4.82
cd %{_builddir}/wireplumber-0.4.82
pushd ..
cp -a wireplumber-0.4.82 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707948222
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dsystem-lua=true \
-Delogind=disabled  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dsystem-lua=true \
-Delogind=disabled  builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/wireplumber
cp %{_builddir}/wireplumber-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/wireplumber/eba84e7971aadceae1afd0226007498a4c1ed96b || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang wireplumber
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/user/pipewire.service.wants
ln -s ../wireplumber.service %{buildroot}/usr/lib/systemd/user/pipewire.service.wants/
ln -s wireplumber.service %{buildroot}/usr/lib/systemd/user/pipewire-session-manager.service
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/wireplumber
/V3/usr/bin/wpctl
/V3/usr/bin/wpexec
/usr/bin/wireplumber
/usr/bin/wpctl
/usr/bin/wpexec

%files data
%defattr(-,root,root,-)
/usr/share/pipewire/wireplumber.conf
/usr/share/pipewire/wireplumber.conf.d/alsa-vm.conf
/usr/share/wireplumber/scripts/client/access-default.lua
/usr/share/wireplumber/scripts/client/access-portal.lua
/usr/share/wireplumber/scripts/client/access-snap.lua
/usr/share/wireplumber/scripts/default-nodes/apply-default-node.lua
/usr/share/wireplumber/scripts/default-nodes/find-best-default-node.lua
/usr/share/wireplumber/scripts/default-nodes/find-selected-default-node.lua
/usr/share/wireplumber/scripts/default-nodes/rescan.lua
/usr/share/wireplumber/scripts/default-nodes/state-default-nodes.lua
/usr/share/wireplumber/scripts/device/apply-profile.lua
/usr/share/wireplumber/scripts/device/apply-routes.lua
/usr/share/wireplumber/scripts/device/autoswitch-bluetooth-profile.lua
/usr/share/wireplumber/scripts/device/find-best-profile.lua
/usr/share/wireplumber/scripts/device/find-best-routes.lua
/usr/share/wireplumber/scripts/device/find-preferred-profile.lua
/usr/share/wireplumber/scripts/device/select-profile.lua
/usr/share/wireplumber/scripts/device/select-routes.lua
/usr/share/wireplumber/scripts/device/state-profile.lua
/usr/share/wireplumber/scripts/device/state-routes.lua
/usr/share/wireplumber/scripts/fallback-sink.lua
/usr/share/wireplumber/scripts/intended-roles.lua
/usr/share/wireplumber/scripts/lib/common-utils.lua
/usr/share/wireplumber/scripts/lib/device-info-cache.lua
/usr/share/wireplumber/scripts/lib/filter-utils.lua
/usr/share/wireplumber/scripts/lib/linking-utils.lua
/usr/share/wireplumber/scripts/lib/monitor-utils.lua
/usr/share/wireplumber/scripts/lib/settings-bluetooth.lua
/usr/share/wireplumber/scripts/lib/settings-device.lua
/usr/share/wireplumber/scripts/lib/settings-linking.lua
/usr/share/wireplumber/scripts/lib/settings-manager.lua
/usr/share/wireplumber/scripts/lib/settings-monitor.lua
/usr/share/wireplumber/scripts/lib/settings-node.lua
/usr/share/wireplumber/scripts/linking/find-best-target.lua
/usr/share/wireplumber/scripts/linking/find-default-target.lua
/usr/share/wireplumber/scripts/linking/find-defined-target.lua
/usr/share/wireplumber/scripts/linking/find-filter-target.lua
/usr/share/wireplumber/scripts/linking/find-user-target.lua.example
/usr/share/wireplumber/scripts/linking/find-virtual-target.lua
/usr/share/wireplumber/scripts/linking/get-filter-from-target.lua
/usr/share/wireplumber/scripts/linking/link-target.lua
/usr/share/wireplumber/scripts/linking/prepare-link.lua
/usr/share/wireplumber/scripts/linking/rescan-virtual-links.lua
/usr/share/wireplumber/scripts/linking/rescan.lua
/usr/share/wireplumber/scripts/metadata.lua
/usr/share/wireplumber/scripts/monitors/alsa-midi.lua
/usr/share/wireplumber/scripts/monitors/alsa.lua
/usr/share/wireplumber/scripts/monitors/bluez-midi.lua
/usr/share/wireplumber/scripts/monitors/bluez.lua
/usr/share/wireplumber/scripts/monitors/libcamera/create-device.lua
/usr/share/wireplumber/scripts/monitors/libcamera/create-node.lua
/usr/share/wireplumber/scripts/monitors/libcamera/enumerate-device.lua
/usr/share/wireplumber/scripts/monitors/libcamera/name-device.lua
/usr/share/wireplumber/scripts/monitors/libcamera/name-node.lua
/usr/share/wireplumber/scripts/monitors/v4l2/create-device.lua
/usr/share/wireplumber/scripts/monitors/v4l2/create-node.lua
/usr/share/wireplumber/scripts/monitors/v4l2/enumerate-device.lua
/usr/share/wireplumber/scripts/monitors/v4l2/name-device.lua
/usr/share/wireplumber/scripts/monitors/v4l2/name-node.lua
/usr/share/wireplumber/scripts/node/create-item.lua
/usr/share/wireplumber/scripts/node/create-virtual-item.lua
/usr/share/wireplumber/scripts/node/filter-forward-format.lua
/usr/share/wireplumber/scripts/node/state-stream.lua
/usr/share/wireplumber/scripts/node/suspend-node.lua
/usr/share/wireplumber/scripts/policy-dsp.lua
/usr/share/wireplumber/scripts/sm-objects.lua
/usr/share/zsh/site-functions/_wpctl

%files dev
%defattr(-,root,root,-)
/usr/include/wireplumber-0.5/wp/client.h
/usr/include/wireplumber-0.5/wp/component-loader.h
/usr/include/wireplumber-0.5/wp/conf.h
/usr/include/wireplumber-0.5/wp/core.h
/usr/include/wireplumber-0.5/wp/defs.h
/usr/include/wireplumber-0.5/wp/device.h
/usr/include/wireplumber-0.5/wp/error.h
/usr/include/wireplumber-0.5/wp/event-dispatcher.h
/usr/include/wireplumber-0.5/wp/event-hook.h
/usr/include/wireplumber-0.5/wp/event.h
/usr/include/wireplumber-0.5/wp/factory.h
/usr/include/wireplumber-0.5/wp/global-proxy.h
/usr/include/wireplumber-0.5/wp/iterator.h
/usr/include/wireplumber-0.5/wp/json-utils.h
/usr/include/wireplumber-0.5/wp/link.h
/usr/include/wireplumber-0.5/wp/log.h
/usr/include/wireplumber-0.5/wp/metadata.h
/usr/include/wireplumber-0.5/wp/module.h
/usr/include/wireplumber-0.5/wp/node.h
/usr/include/wireplumber-0.5/wp/object-interest.h
/usr/include/wireplumber-0.5/wp/object-manager.h
/usr/include/wireplumber-0.5/wp/object.h
/usr/include/wireplumber-0.5/wp/plugin.h
/usr/include/wireplumber-0.5/wp/port.h
/usr/include/wireplumber-0.5/wp/properties.h
/usr/include/wireplumber-0.5/wp/proxy-interfaces.h
/usr/include/wireplumber-0.5/wp/proxy.h
/usr/include/wireplumber-0.5/wp/session-item.h
/usr/include/wireplumber-0.5/wp/settings.h
/usr/include/wireplumber-0.5/wp/si-factory.h
/usr/include/wireplumber-0.5/wp/si-interfaces.h
/usr/include/wireplumber-0.5/wp/spa-json.h
/usr/include/wireplumber-0.5/wp/spa-pod.h
/usr/include/wireplumber-0.5/wp/spa-type.h
/usr/include/wireplumber-0.5/wp/state.h
/usr/include/wireplumber-0.5/wp/transition.h
/usr/include/wireplumber-0.5/wp/wp.h
/usr/include/wireplumber-0.5/wp/wpenums.h
/usr/include/wireplumber-0.5/wp/wpversion.h
/usr/lib64/libwireplumber-0.5.so
/usr/lib64/pkgconfig/wireplumber-0.5.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/wireplumber/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libwireplumber-0.5.so.0.4.82
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-dbus-connection.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-default-nodes-api.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-file-monitor-api.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-log-settings.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-logind.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-lua-scripting.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-mixer-api.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-portal-permissionstore.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-reserve-device.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-settings.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-si-audio-adapter.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-si-audio-virtual.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-si-node.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-si-standard-link.so
/V3/usr/lib64/wireplumber-0.5/libwireplumber-module-standard-event-source.so
/usr/lib64/libwireplumber-0.5.so.0
/usr/lib64/libwireplumber-0.5.so.0.4.82
/usr/lib64/wireplumber-0.5/libwireplumber-module-dbus-connection.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-default-nodes-api.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-file-monitor-api.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-log-settings.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-logind.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-lua-scripting.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-mixer-api.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-portal-permissionstore.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-reserve-device.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-settings.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-si-audio-adapter.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-si-audio-virtual.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-si-node.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-si-standard-link.so
/usr/lib64/wireplumber-0.5/libwireplumber-module-standard-event-source.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/wireplumber/eba84e7971aadceae1afd0226007498a4c1ed96b

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/pipewire-session-manager.service
/usr/lib/systemd/user/pipewire.service.wants/wireplumber.service
/usr/lib/systemd/user/wireplumber.service
/usr/lib/systemd/user/wireplumber@.service

%files locales -f wireplumber.lang
%defattr(-,root,root,-)

